### ISSUE TITLE
Add Kirby Block-Preview

### ISSUE THREAD

**Issue by hariom147** [fabianmichael/kirby-markdown-field#109]
Any chance, that this great plugin will get a block-preview for Kirby blocks, introduced with Kirby 3.5?
Unfortunately that's beyond my capabilities...

**Comment by hansgohr** [comment]
actually it's pretty straight forward if you follow the basic block preview guide: 

https://getkirby.com/docs/reference/plugins/extensions/blocks

I just gave it a try and it works like with any other custom block preview.

**Comment by fabianmichael** [comment]
@lucadorata Do you mean, that the plugin should provide a Markdown block, which uses our editor?

@lucadorata @hansgohr Getting a proper preview for the Markdown field might be a bit harder, because the field value has to be parsed server-side in order to get the resulting HTML. This probably would require us to define a route/API endpoint, which is capable of returning the corresponding HTML. The preview has to fetch this, whenever the field value changes (debounced, of course).

**Comment by lucadorata** [comment]
@fabianmichael As you stated in your answer, that is what I meant: A built-in kirby-block with vue-like editable preview.
But actually preview would be enough (doesn't have to be editable), i.e. so that the content of the markdown-field will be rendered as html in the block-preview.
I don't understand enough of the backend-principles, but would a [vue-markdown-preview](https://miaolz123.github.io/vue-markdown/) be of any help to achieve this?

**Comment by fabianmichael** [comment]
@lucadorata Kirby’s Markdown is an extended version, which is parsed in PHP and thus cannot be rendered by a JS-based parser alone, because of Kirbytags (e.g. `(image: …)`). Kirbytags can be extended and customized by the user and do complex things, like pulling in data from other pages, generate thumbnails etc. So the only solution for getting a proper preview would be to let the server render the corresponding preview. The only alternative I would think of, would be to just skip Kirbytags for the preview (maybe highlight them using a regular expression) and use the JS-based parser for realtime-previews. This would also solve the problems of having custom Kirbytags, which could theoretically break the layout because their CSS is not loaded in the panel.

@sylvainjule What do you think?

**Comment by fabianmichael** [comment]
@lucadorata FYI, a new version of the plugin has now reached late alpha/early beta., based on CodeMirror 6. It replaces Kirby’s Markdown block with one, that uses our advanced editor. If you’re adventurous, you should give it a try: https://github.com/sylvainjule/kirby-markdown-field/tree/next

**Comment by lucadorata** [comment]
> @lucadorata FYI, a new version of the plugin has now reached late alpha/early beta., based on CodeMirror 6. It replaces Kirby’s Markdown block with one, that uses our advanced editor. If you’re adventurous, you should give it a try: https://github.com/sylvainjule/kirby-markdown-field/tree/next
Thanks! I will.

**Comment by fabianmichael** [comment]
Closing this, as the PR has already been merged.
