### ISSUE TITLE
[next| Compatibility with Kirby 3.6

### ISSUE THREAD

**Issue by fabianmichael** [fabianmichael/kirby-markdown-field#116]
It needs to be tested, whether the field is compatible with the upcoming Kirby version. At least the `font` option does not work at the moment.

**Comment by herrajon** [comment]
Neither does the link option

`undefined is not an object (evaluating 'this.$store.state.system.info')`

**Comment by fabianmichael** [comment]
Does anyone still have issues with 3.6.x? If not, I would like to close this ticket. The final release of 2.0 of this field should happen quite soon now … :-)

**Comment by sebastiangreger** [comment]
@fabianmichael I have not worked with Markdown texts a lot since updating to 3.6, but at least haven't noticed any obvious issues. There are a few little glitches that I haven't really been able to pinpoint quite yet, but those are merely aesthetic and likely not 3.6-related (I'll try to follow up on them in separate issues at some point).

**Comment by fabianmichael** [comment]
@afbora @bastianallgeier @lukasbestle As there have been no further complaints and I’ve been using the plugin with 3.6 for some time now, I’ll close this. It’s safe to assume, that the Markdown Field 2.0 is fully compatible with Kirby 3.6.
