### ISSUE TITLE
Remove the narrow layout?

### ISSUE THREAD

**Issue by medienbaecker** [fabianmichael/kirby-markdown-field#143]
Sorry for the provocative issue title.

I noticed some issues with the cursor position caused by the `narrow` layout option. It doesn't seem to be easy to fix unfortunately. CodeMirror doesn't like the two editor sizes at all. You're using [a ResizeObserver](https://github.com/fabianmichael/kirby-markdown-field/blob/43bf7b673aaaee14847551258d086ac8f37196ff/src/components/MarkdownInput.vue#L85-L91) which sometimes doesn't trigger (or triggers too early?) so it displays the cursor at the "narrow" position until you start typing:

<img width="760" src="https://user-images.githubusercontent.com/7975568/168889108-384e9d99-19c1-4713-8b02-200f3ed1963b.png">

So I'm wondering what's the purpose of the narrow layout? It's triggered when the field is less than 450px wide and looks very crammed in my opinion. It also doesn't provide that much more space:

<img width="375" src="https://user-images.githubusercontent.com/7975568/168888623-1add4d23-8ed0-4ae5-9d63-bf1086984c1d.png">

What do you think?

**Comment by medienbaecker** [comment]
I see. Then I think it would make sense to further align the field to the regular textarea and use one layout only. Currently the horizontal padding is slightly smaller and the vertical padding is larger.

What do you think? I can create a PR for the style adjustments.

![markdown-textarea](https://user-images.githubusercontent.com/7975568/170938954-36ac3eb9-dab6-4b4f-a45c-94c5bc224038.gif)

**Comment by fabianmichael** [comment]
@medienbaecker Yeah, let’s do this. Unfortunately, CodeMirror introduced a lot of breaking changes lately. So the step from 0.19 to 0.20 requires me to overhaul quite a few parts of the codebase. Honestly, I got zero motivation for this, but otherwise the plugin will be cut-off from any further updates. So it might be a good idea to wait with this until I’ve updated all the plugin logic, as it also affects theming. But I really don’t know, when I’ll find the motivation and time for working on this … you can track the progress in the https://github.com/fabianmichael/kirby-markdown-field/tree/feature/disabled-state branch. If you want to step in to help any further with the project, I’m not holding you back. ;-)

**Comment by fabianmichael** [comment]
@medienbaecker Everything is merged, you can begin to update the style if you want. :-)
