### ISSUE TITLE
3.7 compatibility; error on frontend

### ISSUE THREAD

**Issue by S1SYPHOS** [fabianmichael/kirby-markdown-field#147]
Hey there,
when I update Kirby to v3.7, this plugin throws an `Exception`. Now, there's two things about that:

1) README states 'Kirby 3.6 or higher', but what it means is 'Kirby 3.6.x'
2) This affects the frontend (= site not working) while it should affect only the backend (= field not working).

I think 1) will go away when 3.7 compatibility arrives in the future, but 2) is something that I cannot provide a PR due to lacking JS skills - yes, it weighs heavy on my shoulders, but I (kind of) despise it.

Thanks for listening to my feedback, and also for (taking over) this project, dear @fabianmichael!

Cheers,
S1SYPHOS

**Comment by fabianmichael** [comment]
Hi @S1SYPHOS,

> README states 'Kirby 3.6 or higher', but what it means is 'Kirby 3.6.x'

It actually says `This version of the plugin requires PHP 8.0 and Kirby 3.6.0 or higher.`, which includes all 3.6.x versions for sure.

> This affects the frontend (= site not working) while it should affect only the backend (= field not working).

As the front-end does not load any of the plugin’s JS code, so that cannot be the reaso why your site is crashing (it could only crash the panel). But there could be some compatibility issue hidden within the PHP code. Please enable debugging and have a look at the error screen.

If you have installed the field using composer, please be aware that up until now the last stable version was 1.x. I’ve just added a stable 2.0.0 release, so composer users will get the correct version from now on.

**Comment by S1SYPHOS** [comment]
Thanks! Anything I could do to help?

**Comment by fabianmichael** [comment]
@S1SYPHOS

> As the front-end does not load any of the plugin’s JS code, so that cannot be the reaso why your site is crashing (it could only crash the panel). But there could be some compatibility issue hidden within the PHP code. Please enable debugging and have a look at the error screen.

**Comment by S1SYPHOS** [comment]
Seems that Composer / Packagist don't know of the new release, which would be helpful to people installing v2 :smile:
