### ISSUE TITLE
Disabled Field appears "disabled" but content is still editable

### ISSUE THREAD

**Issue by teichsta** [fabianmichael/kirby-markdown-field#168]
`disabled` is set to `true` and field appears to be disabled:

![image](https://user-images.githubusercontent.com/2108636/224123144-fce932a9-687d-45c6-8d31-14a6d2c73f9e.png)

nevertheless the content is still editable:

![image](https://user-images.githubusercontent.com/2108636/224123271-6feb2bfa-285e-413a-a154-5174230414e0.png)

and model is set `dirty`. It boils down to the fact that `contenteditable` attribute is still set to `true` 

![image](https://user-images.githubusercontent.com/2108636/224123689-454b7c49-9b86-4816-961f-d2caef0829f8.png)

When changing this attribute to `false` (manually) the editor isn't editable anymore (as expected).

Any idea how to fix this @fabianmichael ?

**Comment by fabianmichael** [comment]
@teichsta TL;DR: Feel free to submit a PR, that updates the editor HTML manually, if this is urgent.

Long story: CodeMirror has seen quite a few releases that have probably changes quite a bit as well. The editor plugin currently uses 6.1.4 and CM is currently at 6.9.2 (and this bug has probably been tackled in the meantime). I will need some time for updating all the packages, which probably involves quite a bit of rewriting the editor itself. But since I am currently stuck in my daily work. I cannot give you any ETA on this. It will probably take a few months at best, until I’ll find the time for doing this huge update.

**Comment by teichsta** [comment]
this seems to be a kirby bug (see https://forum.getkirby.com/t/how-to-disable-all-blocks-in-a-blocks-field/28081). In my case i use the `MarkdownBlock` which doesn't get disabled through its surrounding `BlocksField`.
