### ISSUE TITLE
Nested lists

### ISSUE THREAD

**Issue by timotheegoguely** [fabianmichael/kirby-markdown-field#171]
The following markdown is rendered is 2 consecutive lists instead of a proper nested list:

```md
1. Item
2. Item
3. Item
    - Item
    - Item
    - Item
```

```md
- Item
- Item
- Item
    1. Item
    2. Item
    3. Item
```

Actual output:
```html
<ol>
  <li>Item</li>
  <li>Item</li>
  <li>Item</li>
</ol>
<ul>
  <li>Item</li>
  <li>Item</li>
  <li>Item</li>
</ul>
```

```html
<ul>
  <li>Item</li>
  <li>Item</li>
  <li>Item</li>
</ul>
<ol>
  <li>Item</li>
  <li>Item</li>
  <li>Item</li>
</ol>
```

Expected output:
```html
<ol>
  <li>Item</li>
  <li>Item</li>
  <li>
    <ul>
      <li>Item</li>
      <li>Item</li>
      <li>Item</li>
    </ul>
  </li>
</ol>
```

```html
<ul>
  <li>Item</li>
  <li>Item</li>
  <li>
    <ol>
      <li>Item</li>
      <li>Item</li>
      <li>Item</li>
    </ol>
  </li>
</ul>
```

**Comment by fabianmichael** [comment]
@timotheegoguely The markdown is actually rendered by Kirby itself and not my plugin and Kirby currently uses a library called Parsedown for that. It would be a great help, if you could find out what formatting is acutally needed in order to procude the expected markup. If you provide me that, I would be happy to update the field’s behavior. Thanks :-)

**Comment by fabianmichael** [comment]
@timotheegoguely Since my plugin only provides the markdown field and has nothing to do with Kirby’s markdown parser, there is always a little chance for the PHP parser to behave a bit differently from the JS syntax highlighter used by the field. If you got a few minutes, please provide me an example of a nested list that is interpreted correctly by Kirby. That would make it easier for me, since my resources are quite limited at the moment.

**Comment by fabianmichael** [comment]
Closing this, as there has not been any activity and not scope of the plugin.
