### ISSUE TITLE
Formatting characters in Kirbytags

### ISSUE THREAD

**Issue by medienbaecker** [fabianmichael/kirby-markdown-field#65]
Writing something like `target: _blank` in e.g. a `link` Kirbytag will make the text after the paranthesis italic. Example:

![image](https://user-images.githubusercontent.com/7975568/52942327-164a5c00-336b-11e9-923b-fdf801e48a43.png)

**Comment by trych** [comment]
To maybe give this a little bump: I have this issue, too, as well as some other users on the Kirby forums.

**Comment by fabianmichael** [comment]
@trych Sorry, that this has not been tackled yet. I’m currently holding back from fixing anything, as CodeMirror 6 will soon arrive at our doorsteps (see https://codemirror.net/6/). It’s probably more feasible for us to focus on using the new CodeMirror version für the plugin as soon as the docs are ready, instead of investing lots of time in fixing the Markdown Parser in the old version.

**Comment by sylvainjule** [comment]
In the meantime, for this specific case I've told editors to write:

`(link: https://... target: blank)`

And in a plugin.php:

```php
'hooks' => [
        'kirbytext:before' => function ($text) {
            $text = str_replace('target: blank', 'target: _blank', $text);
            return $text;
        },
```

**Comment by fabianmichael** [comment]
@medienbaecker FYI: This will be resolved in the upcoming version 2 of the plugin, currently in late alpha/early beta, see https://github.com/sylvainjule/kirby-markdown-field/tree/next

**Comment by fabianmichael** [comment]
Closing this, as it seemingly affects version 1.0. Version 2 will be released soon, so I won’t go into that any further. Thanks for your understanding.
